backend:
  name: git-gateway
  branch: panelbranch

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "home"
    label: "Encabezado Principal"
    files:
      - label: "Inicio"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Imagen de Encabezado", name: "header_image", widget: "image" }

  - name: "projects"
    label: "Proyectos"
    files:
      - label: "Lista de Proyectos"
        name: "projects"
        file: "content/projects.md"
        fields:
          - { label: "Título Proyecto Destacado", name: "project_1_title", widget: "string" }
          - { label: "Imagen Proyecto Destacado", name: "project_1_image", widget: "image" }
          - { label: "Descripción Proyecto Destacado", name: "project_1_text", widget: "text" }

          - { label: "Título Proyecto Uno", name: "project_2_title", widget: "string" }
          - { label: "Imagen Proyecto Uno", name: "project_2_image", widget: "image" }
          - { label: "Descripción Proyecto Uno", name: "project_2_text", widget: "text" }

          - { label: "Título Proyecto Dos", name: "project_3_title", widget: "string" }
          - { label: "Imagen Proyecto Dos", name: "project_3_image", widget: "image" }
          - { label: "Descripción Proyecto Dos", name: "project_3_text", widget: "text" }
